// One valid event of every supported type, with synthetic values. Shared by
// validation, encoding, fingerprint and projection tests.

import type { Envelope } from "../src/schema/envelope.js";
import type { LedgerEvent, SupportedEvent } from "../src/schema/events.js";
import { DEFAULT_SETTINGS } from "../src/settings/settings.js";

export const ID = {
  account: "01ARYZ6S41TSV4RRFFQ69G5FA0",
  account2: "01ARYZ6S41TSV4RRFFQ69G5FA1",
  asset: "01ARYZ6S41TSV4RRFFQ69G5FA2",
  asset2: "01ARYZ6S41TSV4RRFFQ69G5FA3",
  settings: "01ARYZ6S41TSV4RRFFQ69G5FA4",
  buy: "01ARYZ6S41TSV4RRFFQ69G5FA5",
  sell: "01ARYZ6S41TSV4RRFFQ69G5FA6",
  transfer: "01ARYZ6S41TSV4RRFFQ69G5FA7",
  dividend: "01ARYZ6S41TSV4RRFFQ69G5FA8",
  interest: "01ARYZ6S41TSV4RRFFQ69G5FA9",
  fx: "01ARYZ6S41TSV4RRFFQ69G5FAA",
  deposit: "01ARYZ6S41TSV4RRFFQ69G5FAB",
  withdrawal: "01ARYZ6S41TSV4RRFFQ69G5FAC",
  fee: "01ARYZ6S41TSV4RRFFQ69G5FAD",
  valuation: "01ARYZ6S41TSV4RRFFQ69G5FAE",
  order: "01ARYZ6S41TSV4RRFFQ69G5FAF",
  orderUpdate: "01ARYZ6S41TSV4RRFFQ69G5FAG",
  request: "01ARYZ6S41TSV4RRFFQ69G5FAH",
  requestUpdate: "01ARYZ6S41TSV4RRFFQ69G5FAJ",
  reversal: "01ARYZ6S41TSV4RRFFQ69G5FAK",
} as const;

export const envelope = (id: string, type: LedgerEvent["type"]): Envelope => ({
  schema_version: 1,
  id,
  recorded_at: "2026-09-01T18:22:05.000Z",
  type,
});

export const SAMPLES: { [T in SupportedEvent["type"]]: Extract<SupportedEvent, { type: T }> } = {
  account_created: {
    ...envelope(ID.account, "account_created"),
    type: "account_created",
    account_id: "acc_fund",
    name: "Fondos",
    platform: "myinvestor",
    book: "core",
    base_currency: "EUR",
    country: "ES",
    active: true,
  },
  account_updated: {
    ...envelope(ID.account2, "account_updated"),
    type: "account_updated",
    account_id: "acc_fund",
    name: "Fondos indexados",
    platform: "myinvestor",
    book: "core",
    base_currency: "EUR",
    country: "ES",
    active: true,
  },
  asset_created: {
    ...envelope(ID.asset, "asset_created"),
    type: "asset_created",
    asset_id: "ast_world",
    asset_type: "fund",
    book: "core",
    asset_class: "equity",
    isin: "XX0000000001",
    name: "World Index",
    currency: "EUR",
    ter: "0.12",
    transferable: true,
    active: true,
  },
  asset_updated: {
    ...envelope(ID.asset2, "asset_updated"),
    type: "asset_updated",
    asset_id: "ast_world",
    asset_type: "fund",
    book: "core",
    asset_class: "equity",
    isin: "XX0000000009",
    name: "World Index",
    currency: "EUR",
    transferable: true,
    active: true,
  },
  settings_changed: {
    ...envelope(ID.settings, "settings_changed"),
    type: "settings_changed",
    settings: DEFAULT_SETTINGS,
  },
  buy: {
    ...envelope(ID.buy, "buy"),
    type: "buy",
    account_id: "acc_fund",
    asset_id: "ast_world",
    trade_date: "2026-09-01",
    value_date: "2026-09-02",
    quantity: "10.123456",
    unit_price: "98.78",
    amount: "1000",
    currency: "EUR",
    fx_rate: "1",
    fx_rate_date: "2026-09-02",
    fee: "0",
    fingerprint: "sha256:0",
    source: "manual",
  },
  sell: {
    ...envelope(ID.sell, "sell"),
    type: "sell",
    account_id: "acc_fund",
    asset_id: "ast_world",
    trade_date: "2027-02-01",
    value_date: "2027-02-03",
    quantity: "2",
    unit_price: "110",
    currency: "EUR",
    fx_rate: "1",
    fx_rate_date: "2027-02-03",
    fee: "0",
    withholding: "3.80",
    fingerprint: "sha256:1",
    source: "manual",
  },
  transfer: {
    ...envelope(ID.transfer, "transfer"),
    type: "transfer",
    from_account_id: "acc_fund",
    from_asset_id: "ast_world",
    quantity_out: "4",
    nav_out: "105",
    value_date_out: "2027-03-03",
    to_account_id: "acc_fund",
    to_asset_id: "ast_bonds",
    quantity_in: "3.5",
    nav_in: "120",
    value_date_in: "2027-03-05",
    fingerprint: "sha256:2",
  },
  dividend: {
    ...envelope(ID.dividend, "dividend"),
    type: "dividend",
    account_id: "acc_etf",
    asset_id: "ast_gold",
    value_date: "2027-04-01",
    gross: "10",
    withholding_origin: "1.5",
    withholding_spain: "1.9",
    currency: "USD",
    fx_rate: "1.0850",
    fx_rate_date: "2027-04-01",
    fingerprint: "sha256:3",
  },
  interest: {
    ...envelope(ID.interest, "interest"),
    type: "interest",
    account_id: "acc_etf",
    value_date: "2027-04-30",
    gross: "5",
    withholding_spain: "0.95",
    currency: "EUR",
    fx_rate: "1",
    fx_rate_date: "2027-04-30",
    fingerprint: "sha256:4",
  },
  fx_exchange: {
    ...envelope(ID.fx, "fx_exchange"),
    type: "fx_exchange",
    account_id: "acc_etf",
    value_date: "2027-05-02",
    sold_amount: "1085",
    sold_currency: "EUR",
    bought_amount: "1170",
    bought_currency: "USD",
    fee: "2",
    fee_currency: "USD",
    fx_rate_sold: "1",
    fx_rate_bought: "1.0783",
    fx_rate_date: "2027-05-02",
    fingerprint: "sha256:5",
  },
  cash_deposit: {
    ...envelope(ID.deposit, "cash_deposit"),
    type: "cash_deposit",
    account_id: "acc_fund",
    value_date: "2026-08-31",
    amount: "5000",
    currency: "EUR",
    fx_rate: "1",
    fingerprint: "sha256:6",
  },
  cash_withdrawal: {
    ...envelope(ID.withdrawal, "cash_withdrawal"),
    type: "cash_withdrawal",
    account_id: "acc_fund",
    value_date: "2027-06-01",
    amount: "100",
    currency: "EUR",
    fx_rate: "1",
    fingerprint: "sha256:7",
  },
  standalone_fee: {
    ...envelope(ID.fee, "standalone_fee"),
    type: "standalone_fee",
    account_id: "acc_etf",
    value_date: "2027-06-30",
    amount: "3",
    currency: "EUR",
    fx_rate: "1",
    description: "custody",
    fingerprint: "sha256:8",
  },
  valuation: {
    ...envelope(ID.valuation, "valuation"),
    type: "valuation",
    account_id: "acc_etf",
    asset_id: "ast_gold",
    date: "2026-12-31",
    quantity: "5",
    unit_value: "210",
    currency: "USD",
    fx_rate: "1.0900",
    source: "manual",
  },
  order_placed: {
    ...envelope(ID.order, "order_placed"),
    type: "order_placed",
    account_id: "acc_fund",
    asset_id: "ast_world",
    side: "buy",
    amount: "500",
    requested_date: "2027-07-01",
  },
  order_updated: {
    ...envelope(ID.orderUpdate, "order_updated"),
    type: "order_updated",
    order_id: ID.order,
    stage: "cancelled",
    date: "2027-07-02",
  },
  transfer_requested: {
    ...envelope(ID.request, "transfer_requested"),
    type: "transfer_requested",
    from_account_id: "acc_fund",
    from_asset_id: "ast_world",
    to_account_id: "acc_fund",
    to_asset_id: "ast_bonds",
    quantity_out: "4",
    requested_date: "2027-03-01",
  },
  transfer_request_updated: {
    ...envelope(ID.requestUpdate, "transfer_request_updated"),
    type: "transfer_request_updated",
    request_id: ID.request,
    stage: "redeemed",
    date: "2027-03-03",
    nav_out: "105",
  },
  reversal: {
    ...envelope(ID.reversal, "reversal"),
    type: "reversal",
    reverses_id: ID.sell,
    reason: "precio mal tecleado",
  },
};

export const sampleList = (): SupportedEvent[] => Object.values(SAMPLES);

/** Copy of a sample with fields overridden or removed (`undefined` removes). */
export const variant = <T extends SupportedEvent>(
  sample: T,
  changes: Partial<Record<keyof T | string, unknown>>,
): Record<string, unknown> => {
  const copy: Record<string, unknown> = { ...sample };
  for (const [key, value] of Object.entries(changes)) {
    if (value === undefined) {
      delete copy[key];
    } else {
      copy[key] = value;
    }
  }
  return copy;
};
