#!/usr/bin/env bash
# Validates a commit message file against the project rules:
#  - Conventional Commits subject, in English, <= 72 chars
#  - no AI attribution anywhere in the message
# Usage: validate-commit-message.sh <message-file>
set -u
file="$1"
subject=$(grep -v '^#' "$file" | sed '/^[[:space:]]*$/d' | head -n 1)

if [[ -z "$subject" ]]; then
  echo "commit-msg: empty commit message" >&2
  exit 1
fi

# Merge commits from git flow (--no-ff) are allowed as generated by git.
if [[ "$subject" == Merge\ * ]]; then
  exit 0
fi

types='feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'
pattern="^(${types})(\([a-z0-9._/-]+\))?!?: [^ ].*$"
if ! [[ "$subject" =~ $pattern ]]; then
  echo "commit-msg: subject must follow Conventional Commits: '<type>(<scope>): <summary>'" >&2
  echo "  types: ${types}" >&2
  echo "  got:   '${subject}'" >&2
  exit 1
fi

if (( ${#subject} > 72 )); then
  echo "commit-msg: subject is ${#subject} chars; keep it <= 72" >&2
  exit 1
fi

if grep -v '^#' "$file" | grep -qiE 'co-authored-by|generated with|claude|anthropic|chatgpt|copilot|gemini|cursor'; then
  echo "commit-msg: AI attribution is not allowed in commit messages" >&2
  exit 1
fi

exit 0
